apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: mesh-ex2
  name: mesh-ex2
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8060
  selector:
    app: mesh-ex2
  sessionAffinity: None
  type: ClusterIP
